use_frameworks!

platform :ios, '12.0'

target 'SFStyleKit_Example' do
  pod 'SFStyleKit', :path => '../'
  
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SFStyleKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
